FROM node:22-alpine

WORKDIR /app

# Copia dependências e instala
COPY package.json package-lock.json ./
RUN npm install

# Copia o restante da aplicação
COPY . .

# Exponha a porta usada pelo Vite
EXPOSE 3000

CMD ["npm", "run", "dev"]
