services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

volumes:
  pgdata:
