"""adiciona data_nascimento

Revision ID: 8b183a3fba01
Revises: b3df20222a33
Create Date: 2025-04-25 13:52:00.556038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b183a3fba01'
down_revision: Union[str, None] = 'b3df20222a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('permission', sa.Enum('admin', 'user', 'read', name='permissiontype'), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('reset_password_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_index(op.f('ix_users_data_nascimento'), 'users', ['data_nascimento'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_hashed_password'), 'users', ['hashed_password'], unique=True)
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_reset_password_token'), 'users', ['reset_password_token'], unique=False)
    op.create_index(op.f('ix_users_reset_token_expires_at'), 'users', ['reset_token_expires_at'], unique=False)
    op.create_index(op.f('ix_users_telephone'), 'users', ['telephone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telephone'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token_expires_at'), table_name='users')
    op.drop_index(op.f('ix_users_reset_password_token'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_index(op.f('ix_users_hashed_password'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_data_nascimento'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
