"""removendo coluna cpf e data nascimento

Revision ID: db3c7b160746
Revises: 8b183a3fba01
Create Date: 2025-04-25 14:00:48.074248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db3c7b160746'
down_revision: Union[str, None] = '8b183a3fba01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_cpf', table_name='users')
    op.drop_index('ix_users_data_nascimento', table_name='users')
    op.drop_column('users', 'data_nascimento')
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('data_nascimento', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index('ix_users_data_nascimento', 'users', ['data_nascimento'], unique=False)
    op.create_index('ix_users_cpf', 'users', ['cpf'], unique=True)
    # ### end Alembic commands ###
